apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment-example
  labels:
    run: app
spec:
  replicas: 2
  selector:
    matchLabels:
      run: app
  template:
    metadata:
      labels:
        run: app
    spec:
      containers:
      - name: app
        image: "{{ image_id }}"
